#!/usr/bin/python
import sys
import os

import installer
from installer import installer

def main(argv):
    subprogram, args = check_args(argv)
    subprograms[subprogram](args)

def check_args(args):
    subprogram = args[1]
    args = args[2:]

    return subprogram, args

subprograms = {
        'install': installer.run,
    }

if __name__ == '__main__':
    main(sys.argv)
