import os

#########################
# DO NOT EDIT THIS FILE #
#########################

#Beautiful
NESTCONTROL_PATH= "/".join(os.path.abspath(__file__).split("/")[:-1])

INSTALLER_PATH=NESTCONTROL_PATH+"/installer"
CLEAN_PATH=NESTCONTROL_PATH+"/clean"
DBL_PATH=NESTCONTROL_PATH+"/databaseline"

WORKING_DIR = INSTALLER_PATH+"/working"
DEFAULT_FILES_DIR = INSTALLER_PATH+"/default_files"
DBL_TAR_DIR = NESTCONTROL_PATH+"/dbls"
DBL_FILES_DIR = NESTCONTROL_PATH+"/tmp/dbl"
LOG_DIR = INSTALLER_PATH+"/log"

ADMIN_NAME = "adminuser"
LDAP_ADMIN_NAME = "AdminUser"
LDAP_ROOT_USER_NAME = "adminuser"
LOG_DIR = INSTALLER_PATH + "/log/"
DEFAULT_ADMIN_EMAIL = "NEW_DBADMINUSER@HostName_PLACEHOLDER.Domain_PLACEHOLDER"
DEFAULT_HOSTNAME = "HostName_PLACEHOLDER"
DEFAULT_DOMAIN = "Domain_PLACEHOLDER"
CONFIG_FILE = "./config.conf"
